spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbs?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"

imageurl: "/static/images"